apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
spec:
  selector:
    matchLabels:
      app: polybot
  replicas: 1
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: IMG_URL # TODO change IMG_URL to your polybot image in dockerhub or ECR
